### ISSUE TITLE
Missing neighbors.conf file

### ISSUE THREAD

**Issue by lapngodoan** [ANLAB-KAIST/pspgen-dpdk#1]
Hi,
I'm trying to use your pspgen-dpdk application.
Building is ok but running show me this error:
Cannot open the neighbor configuration file "neighbors.conf"
Can you tell me what is the content of neighbors.conf?
Thank and Best Regards
Lapd

**Comment by achimnol** [comment]
`neighbors.conf` should contain a line-by-line list of pairs of destination MAC address and IP address separated by a single space.
Example:

```
aa:bb:cc:dd:ee:ff 0.0.0.0
aa:bb:cc:ee:dd:ff 0.0.0.0
```

Currently the IP addresses are unused so you may type dummy address such as `0.0.0.0`.
The number of entries must be same to the number of NICs used by the program, as pspgen thinks the NICs of the generator and the target system are connected one-to-one (or back-to-back).
